apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mynginx
  name: mynginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - image: rosesoriano/mynginx:v0.0.1
        name: mynginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: mywebapp1
  labels:
    app: mynginx
spec:
  containers:
  - name: mynginx
    image: rosesoriano/mynginx:v0.0.1
    ports:
      -containerPort: 80